export const quotes = [
    { quote: "Whatever the mind of man can conceive and believe, it can achieve.", author: "Napoleon Hill"},
    { quote: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein"},
    { quote: "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.", author: "Robert Frost"},
    { quote: "I attribute my success to this: I never gave or took any excuse. ", author: "Florence Nightingale"},
    { quote: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart"},
    { quote: "Every strike brings me closer to the next home run.", author: "Babe Ruth"},
    { quote: "Definiteness of purpose is the starting point of all achievement.", author: "W. Clement Stone"},
    { quote: "Life isn't about getting and having, it's about giving and being.", author: "Kevin Kruse"},
    { quote: "Life is what happens to you while you're busy making other plans.", author: "John Lennon"},
    { quote: "We become what we think about.", author: "Earl Nightingale"},
    { quote: "Life is 10% what happens to me and 90% of how I react to it.", author: "Charles Swindoll"},
    { quote: "The most common way people give up their power is by thinking they don't have any.", author: "Alice Walker"},
    { quote: "The mind is everything. What you think you become. ", author: "Buddha"},
    { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb"},
    { quote: "An unexamined life is not worth living.", author: "Socrates"},
    { quote: "Eighty percent of success is showing up.", author: "Woody Allen"},
    { quote: "Your time is limited, so do not waste it living someone else's life.", author: "Steve Jobs"},
    { quote: "Winning isn't everything, but wanting to win is. ", author: "Vince Lombardi"},
    { quote: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey"},
    { quote: "Every child is an artist.  The problem is how to remain an artist once he grows up.", author: "Pablo Picasso"},
    { quote: "Either you run the day, or the day runs you.", author: "Jim Rohn"},
    { quote: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford"},
    { quote: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain"},
    { quote: "Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it.", author: "Johann Wolfgang von Goethe"},
    { quote: "The best revenge is massive success.", author: "Frank Sinatra"},
    { quote: "Life shrinks or expands in proportion to one's courage.", author: "Anais Nin"},
    { quote: "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", author: "Aristotle"},
    { quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson"},
    { quote: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau"},
    { quote: "Certain things catch your eye, but pursue only those that capture the heart.", author: "Ancient Indian Proverb"},
    { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt"},
    { quote: "Everything you've ever wanted is on the other side of fear.", author: "George Addair"},
    { quote: "Teach thy tongue to say I do not know, and thous shalt progress.", author: "Maimonides"},
    { quote: "Start where you are. Use what you have.  Do what you can.", author: "Arthur Ashe"},
    { quote: "Everything has beauty, but not everyone can see.", author: "Confucius"},
    { quote: "When I let go of what I am, I become what I might be.", author: "Lao Tzu"},
    { quote: "Happiness is not something readymade.  It comes from your own actions.", author: "Dalai Lama"},
    { quote: "If you're offered a seat on a rocket ship, don't ask what seat! Just get on.", author: "Sheryl Sandberg"},
    { quote: "If the wind will not serve, take to the oars.", author: "Latin Proverb"},
    { quote: "Too many of us are not living our dreams because we are living our fears.", author: "Les Brown"},
    { quote: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington"},
    { quote: "I didn't fail the test. I just found 100 ways to do it wrong.", author: "Benjamin Franklin"},
    { quote: "In order to succeed, your desire for success should be greater than your fear of failure.", author: "Bill Cosby"},
    { quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein"},
    { quote: "The person who says it cannot be done should not interrupt the person who is doing it.", author: "Chinese Proverb"},
    { quote: "There are no traffic jams along the extra mile.", author: "Roger Staubach"},
    { quote: "It is never too late to be what you might have been.", author: "George Eliot"},
    { quote: "You become what you believe.", author: "Oprah Winfrey"},
    { quote: "I would rather die of passion than of boredom.", author: "Vincent van Gogh"},
    { quote: "Build your own dreams, or someone else will hire you to build theirs.", author: "Farrah Gray"},
    { quote: "Education costs money.  But then so does ignorance", author: "Sir Claus Moser"},
    { quote: "I have learned over the years that when one's mind is made up, this diminishes fear.", author: "Rosa Parks"},
    { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius"},
    { quote: "Remember that not getting what you want is sometimes a wonderful stroke of luck.", author: "Dalai Lama"},
    { quote: "You can't use up creativity.  The more you use, the more you have.", author: "Maya Angelou"},
    { quote: "Dream big and dare to fail.", author: "Norman Vaughan"},
    { quote: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr."},
    { quote: "Do what you can, where you are, with what you have.", author: "Teddy Roosevelt"},
    { quote: "If you do what you've always done, you'll get what you've always gotten.", author: "Tony Robbins"},
    { quote: "Dreaming, after all, is a form of planning.", author: "Gloria Steinem"},
    { quote: "You may be disappointed if you fail, but you are doomed if you don't try.", author: "Beverly Sills"},
    { quote: "Remember no one can make you feel inferior without your consent.", author: "Eleanor Roosevelt"},
    { quote: "Life is what we make it, always has been, always will be.", author: "Grandma Moses"},
    { quote: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand"},
    { quote: "It's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln"},
    { quote: "Change your thoughts and you change your world.", author: "Norman Vincent Peale"},
    { quote: "Either write something worth reading or do something worth writing.", author: "Benjamin Franklin"},
    { quote: "Nothing is impossible, the word itself says, “I'm possible!”", author: "Audrey Hepburn"},
    { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs"},
    { quote: "If you can dream it, you can achieve it.", author: "Zig Ziglar"},
    { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde"},
    { quote: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi"},
    { quote: "We accept the love we think we deserve.", author: "Stephen Chbosky"},
    { quote: "Without music, life would be a mistake.", author: "Friedrich Nietzsche"},
    { quote: "We are all in the gutter, but some of us are looking at the stars.", author: " Oscar Wilde"},
    { quote: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison"},
    { quote: "It is never too late to be what you might have been.", author: "George Eliot"},
    { quote: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou"},
    { quote: "Everything you can imagine is real.", author: "Pablo Picasso"},
    { quote: "You can never get a cup of tea large enough or a book long enough to suit me.", author: "C.S. Lewis"},
    { quote: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw"},
    { quote: "To the well-organized mind, death is but the next great adventure.", author: "J.K. Rowling"},
    { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston S. Churchill"},
    { quote: "It's no use going back to yesterday, because I was a different person then.", author: "Lewis Carroll"},
    { quote: "It's the possibility of having a dream come true that makes life interesting.", author: "Paulo Coelho"},
    { quote: "A person's a person, no matter how small.", author: "Dr. Seuss"},
    { quote: "Do what you feel in your heart to be right for you'll be criticized anyway.", author: "Eleanor Roosevelt"},
    { quote: "Peace begins with a smile.", author: "Mother Teresa"},
    { quote: "Who controls the past controls the future. Who controls the present controls the past.", author: "George Orwell"},
    { quote: "Whatever you are, be a good one.", author: "Abraham Lincoln"},
    { quote: "Two wrongs don't make a right, but they make a good excuse.", author: "Thomas Szasz"},
    { quote: "If my life is going to mean anything, I have to live it myself.", author: "Rick Riordan"},
    { quote: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett"},
    { quote: "First they ignore you. Then they ridicule you. And then they attack you and want to burn you. And then they build monuments to you.", author: "Nicholas Klein"},
    { quote: "Hell is empty and all the devils are here.", author: "William Shakespeare"},
    { quote: "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.", author: "John Milton"},
    { quote: "Always do what you are afraid to do.", author: "Ralph Waldo Emerson"},
    { quote: "Talent hits a target no one else can hit. Genius hits a target no one else can see.", author: "Arthur Schopenhauer"},
    { quote: "To be, or not to be: that is the question.", author: "William Shakespeare" },
    { quote: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.", author: "Jane Austen" },
    { quote: "All happy families are alike; each unhappy family is unhappy in its own way.", author: "Leo Tolstoy" },
    { quote: "It was the best of times, it was the worst of times.", author: "Charles Dickens" },
    { quote: "I think therefore I am.", author: "René Descartes" }
];