export const quotes = [
    { quote: "You don't have to be brilliant, only a little bit wiser than the other guys, on average, for a long, long time.", author: "Charlie Munger", hint: "Berkshire Hathaway vice chairman" },
    { quote: "Whatever the mind of man can conceive and believe, it can achieve.", author: "Napoleon Hill", hint: "Self-help author" },
    { quote: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein", hint: "Famous physicist" },
    { quote: "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.", author: "Robert Frost", hint: "American poet" },
    { quote: "I attribute my success to this: I never gave or took any excuse. ", author: "Florence Nightingale", hint: "Founder of modern nursing" },
    { quote: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart", hint: "Pioneer aviator" },
    { quote: "Every strike brings me closer to the next home run.", author: "Babe Ruth", hint: "Legendary baseball player" },
    { quote: "Definiteness of purpose is the starting point of all achievement.", author: "W. Clement Stone", hint: "Businessman and self-help author" },
    { quote: "Life isn't about getting and having, it's about giving and being.", author: "Kevin Kruse", hint: "Entrepreneur and author" },
    { quote: "Life is what happens to you while you're busy making other plans.", author: "John Lennon", hint: "Beatles member" },
    { quote: "We become what we think about.", author: "Earl Nightingale", hint: "Radio speaker and author" },
    { quote: "Life is 10% what happens to me and 90% of how I react to it.", author: "Charles Swindoll", hint: "Evangelical Christian pastor" },
    { quote: "The most common way people give up their power is by thinking they don't have any.", author: "Alice Walker", hint: "The Color Purple author" },
    { quote: "The mind is everything. What you think you become. ", author: "Buddha", hint: "Founder of Buddhism" },
    { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", hint: "Traditional wisdom" },
    { quote: "An unexamined life is not worth living.", author: "Socrates", hint: "Ancient Greek philosopher" },
    { quote: "Eighty percent of success is showing up.", author: "Woody Allen", hint: "Film director and comedian" },
    { quote: "Your time is limited, so do not waste it living someone else's life.", author: "Steve Jobs", hint: "Apple co-founder" },
    { quote: "Winning isn't everything, but wanting to win is. ", author: "Vince Lombardi", hint: "Legendary football coach" },
    { quote: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey", hint: "7 Habits author" },
    { quote: "Every child is an artist.  The problem is how to remain an artist once he grows up.", author: "Pablo Picasso", hint: "Spanish painter" },
    { quote: "Either you run the day, or the day runs you.", author: "Jim Rohn", hint: "Motivational speaker" },
    { quote: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford", hint: "Automobile pioneer" },
    { quote: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain", hint: "American writer and humorist" },
    { quote: "Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it.", author: "Johann Wolfgang von Goethe", hint: "German writer and statesman" },
    { quote: "The best revenge is massive success.", author: "Frank Sinatra", hint: "Legendary singer" },
    { quote: "Life shrinks or expands in proportion to one's courage.", author: "Anais Nin", hint: "French-American writer" },
    { quote: "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", author: "Aristotle", hint: "Ancient Greek philosopher" },
    { quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", hint: "American essayist" },
    { quote: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau", hint: "Transcendentalist author" },
    { quote: "Certain things catch your eye, but pursue only those that capture the heart.", author: "Ancient Indian Proverb", hint: "Traditional wisdom" },
    { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", hint: "26th US President" },
    { quote: "Everything you've ever wanted is on the other side of fear.", author: "George Addair", hint: "Motivational speaker" },
    { quote: "Teach thy tongue to say I do not know, and thous shalt progress.", author: "Maimonides", hint: "Medieval Jewish philosopher" },
    { quote: "Start where you are. Use what you have.  Do what you can.", author: "Arthur Ashe", hint: "Tennis champion" },
    { quote: "Everything has beauty, but not everyone can see.", author: "Confucius", hint: "Chinese philosopher" },
    { quote: "When I let go of what I am, I become what I might be.", author: "Lao Tzu", hint: "Founder of Taoism" },
    { quote: "Happiness is not something readymade.  It comes from your own actions.", author: "Dalai Lama", hint: "Tibetan spiritual leader" },
    { quote: "If you're offered a seat on a rocket ship, don't ask what seat! Just get on.", author: "Sheryl Sandberg", hint: "Facebook COO" },
    { quote: "If the wind will not serve, take to the oars.", author: "Latin Proverb", hint: "Ancient wisdom" },
    { quote: "Too many of us are not living our dreams because we are living our fears.", author: "Les Brown", hint: "Motivational speaker" },
    { quote: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington", hint: "African-American educator" },
    { quote: "I didn't fail the test. I just found 100 ways to do it wrong.", author: "Benjamin Franklin", hint: "Founding Father" },
    { quote: "In order to succeed, your desire for success should be greater than your fear of failure.", author: "Bill Cosby", hint: "Comedian and actor" },
    { quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", hint: "Famous physicist" },
    { quote: "The person who says it cannot be done should not interrupt the person who is doing it.", author: "Chinese Proverb", hint: "Traditional wisdom" },
    { quote: "There are no traffic jams along the extra mile.", author: "Roger Staubach", hint: "NFL quarterback" },
    { quote: "It is never too late to be what you might have been.", author: "George Eliot", hint: "Victorian-era novelist" },
    { quote: "You become what you believe.", author: "Oprah Winfrey", hint: "Media mogul" },
    { quote: "I would rather die of passion than of boredom.", author: "Vincent van Gogh", hint: "Dutch painter" },
    { quote: "Build your own dreams, or someone else will hire you to build theirs.", author: "Farrah Gray", hint: "Young entrepreneur" },
    { quote: "Education costs money.  But then so does ignorance", author: "Sir Claus Moser", hint: "British statistician" },
    { quote: "I have learned over the years that when one's mind is made up, this diminishes fear.", author: "Rosa Parks", hint: "Civil rights activist" },
    { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", hint: "Chinese philosopher" },
    { quote: "Remember that not getting what you want is sometimes a wonderful stroke of luck.", author: "Dalai Lama", hint: "Tibetan spiritual leader" },
    { quote: "You can't use up creativity.  The more you use, the more you have.", author: "Maya Angelou", hint: "American poet" },
    { quote: "Dream big and dare to fail.", author: "Norman Vaughan", hint: "Adventurer" },
    { quote: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr.", hint: "Civil rights leader" },
    { quote: "Do what you can, where you are, with what you have.", author: "Teddy Roosevelt", hint: "26th US President" },
    { quote: "If you do what you've always done, you'll get what you've always gotten.", author: "Tony Robbins", hint: "Self-help author" },
    { quote: "Dreaming, after all, is a form of planning.", author: "Gloria Steinem", hint: "Feminist activist" },
    { quote: "You may be disappointed if you fail, but you are doomed if you don't try.", author: "Beverly Sills", hint: "Opera singer" },
    { quote: "Remember no one can make you feel inferior without your consent.", author: "Eleanor Roosevelt", hint: "Former First Lady" },
    { quote: "Life is what we make it, always has been, always will be.", author: "Grandma Moses", hint: "American folk artist" },
    { quote: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand", hint: "Objectivist philosopher" },
    { quote: "It's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln", hint: "16th US President" },
    { quote: "Change your thoughts and you change your world.", author: "Norman Vincent Peale", hint: "Power of Positive Thinking author" },
    { quote: "Either write something worth reading or do something worth writing.", author: "Benjamin Franklin", hint: "Founding Father" },
    { quote: "Nothing is impossible, the word itself says, I'm possible!", author: "Audrey Hepburn", hint: "Actress and humanitarian" },
    { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs", hint: "Apple co-founder" },
    { quote: "If you can dream it, you can achieve it.", author: "Zig Ziglar", hint: "Motivational speaker" },
    { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde", hint: "Irish playwright" },
    { quote: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi", hint: "Indian independence leader" },
    { quote: "We accept the love we think we deserve.", author: "Stephen Chbosky", hint: "Perks of Being a Wallflower author" },
    { quote: "Without music, life would be a mistake.", author: "Friedrich Nietzsche", hint: "German philosopher" },
    { quote: "We are all in the gutter, but some of us are looking at the stars.", author: " Oscar Wilde", hint: "Irish playwright" },
    { quote: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison", hint: "Inventor" },
    { quote: "It is never too late to be what you might have been.", author: "George Eliot", hint: "Victorian-era novelist" },
    { quote: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou", hint: "American poet" },
    { quote: "Everything you can imagine is real.", author: "Pablo Picasso", hint: "Spanish painter" },
    { quote: "You can never get a cup of tea large enough or a book long enough to suit me.", author: "C.S. Lewis", hint: "Narnia author" },
    { quote: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw", hint: "Irish playwright" },
    { quote: "To the well-organized mind, death is but the next great adventure.", author: "J.K. Rowling", hint: "Harry Potter author" },
    { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston S. Churchill", hint: "British Prime Minister" },
    { quote: "It's no use going back to yesterday, because I was a different person then.", author: "Lewis Carroll", hint: "Alice in Wonderland author" },
    { quote: "It's the possibility of having a dream come true that makes life interesting.", author: "Paulo Coelho", hint: "The Alchemist author" },
    { quote: "A person's a person, no matter how small.", author: "Dr. Seuss", hint: "Children's book author" },
    { quote: "Do what you feel in your heart to be right for you'll be criticized anyway.", author: "Eleanor Roosevelt", hint: "Former First Lady" },
    { quote: "Peace begins with a smile.", author: "Mother Teresa", hint: "Catholic nun and saint" },
    { quote: "Who controls the past controls the future. Who controls the present controls the past.", author: "George Orwell", hint: "1984 author" },
    { quote: "Whatever you are, be a good one.", author: "Abraham Lincoln", hint: "16th US President" },
    { quote: "Two wrongs don't make a right, but they make a good excuse.", author: "Thomas Szasz", hint: "Psychiatrist and academic" },
    { quote: "If my life is going to mean anything, I have to live it myself.", author: "Rick Riordan", hint: "Percy Jackson author" },
    { quote: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett", hint: "The Light in the Heart author" },
    { quote: "First they ignore you. Then they ridicule you. And then they attack you and want to burn you. And then they build monuments to you.", author: "Nicholas Klein", hint: "Union activist" },
    { quote: "Hell is empty and all the devils are here.", author: "William Shakespeare", hint: "English playwright" },
    { quote: "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.", author: "John Milton", hint: "Paradise Lost poet" },
    { quote: "Always do what you are afraid to do.", author: "Ralph Waldo Emerson", hint: "American essayist" },
    { quote: "Talent hits a target no one else can hit. Genius hits a target no one else can see.", author: "Arthur Schopenhauer", hint: "German philosopher" },
    { quote: "To be, or not to be: that is the question.", author: "William Shakespeare", hint: "English playwright" },
    { quote: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.", author: "Jane Austen", hint: "Pride and Prejudice author" },
    { quote: "All happy families are alike; each unhappy family is unhappy in its own way.", author: "Leo Tolstoy", hint: "Anna Karenina author" },
    { quote: "It was the best of times, it was the worst of times.", author: "Charles Dickens", hint: "Tale of Two Cities author" },
    { quote: "I think therefore I am.", author: "René Descartes", hint: "French philosopher" },
    { quote: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus", hint: "Stoic philosopher" },
    { quote: "Don't feel harmed, and you haven't been.", author: "Marcus Aurelius", hint: "Roman emperor" },
    { quote: "We must all either wear out or rust out, every one of us. My choice is to wear out.", author: "Theodore Roosevelt", hint: "26th US President" },
    { quote: "Your goal is not to find love, but to remove all barriers which are preventing you from receiving it.", author: "Rumi", hint: "Persian poet" },
    { quote: "Anti-social behavior is a trait of intelligence in a world full of conformists.", author: "Nikola Tesla", hint: "Inventor and engineer" }, ,
    { quote: "Truth and clarity are complementary.", author: "Niels Bohr", hint: "Danish physicist" },
    { quote: "If you are not aggressive, you are not going to make money, and if you are not defensive, you are not going to keep money.", author: "Ray Dalio", hint: "Hedge fund manager" },
    { quote: "Be satisfied with even the smallest progress.", author: "Marcus Aurelius", hint: "Roman emperor" },
    { quote: "Your actions speak so loudly that I cannot hear what you say.", author: "Ralph Waldo Emerson", hint: "American essayist" },
]